services:
  - type: web
    name: private-chat
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:your_app_key_here
services:
  - type: web
    name: private-chat
    runtime: docker
    plan: free
    branch: main
    repo: https://github.com/krish30825/private-chat
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:6p5fZDQvD6Ng2v68VTOvGHkNwHVM9Vk9LNmuOO2zsYQ=
      - key: DB_CONNECTION
        value: sqlite
